"""The review index (SPEC §5.2.5): byte-exact, deterministic, offline.

Records are built directly and injected into the view: parsing is records.parse_record's business, and
the review root's files are a wave-3 concern. Source paths are lower case, so the real
paths.canonical_key (which folds case on Windows) groups and orders them the same on every OS.
"""

from __future__ import annotations


from conftest import SOURCE_REPO, TRACE_PATH, ZERO64, record_data
from kblam import paths, records
from kblam.review_index import HEADER, generate_review_index
from kblam.view import KBView

REVIEW = "research-review"                  # the default [review] root
TRACE = f"{SOURCE_REPO}/{TRACE_PATH}"       # resources/mx-docs/notes/full-scan-trace.md
OTHER = "resources/mx-docs/notes/other-trace.md"


def source(path: str, *, sha256: str = ZERO64, occurrence: int = 1, lines=(3, 3)) -> dict:
    """A `source` mapping naming `path` (SPEC §5.2.3), with the assertion's identity varied."""
    return {"path": path, "sha256": ZERO64, "repo": None, "commit": None, "blob": None, "snapshot": None,
            "assertion": {"lines": list(lines), "text": "the two bytes are equal", "sha256": sha256,
                          "occurrence": occurrence}}


def record(rec_kind: str, rec_id: str, **fields) -> records.Record:
    """A parsed record of `rec_kind` ("SC", "CT" or "CU"), as parse_record returns one, without touching
    a filesystem. `fields` reach record_data; a CT's own `kind` field is set here, because
    record_data's first parameter would capture that name."""
    task_kind = fields.pop("kind", None)
    data = record_data(rec_kind, rec_id, **fields)
    if task_kind is not None:
        data["kind"] = task_kind
    return records.Record(path=f"{REVIEW}/{records.KINDS[rec_kind]}/{rec_id}.yaml", id=rec_id,
                          kind=rec_kind, data=data, raw=b"")


def view_of(kb, recs) -> KBView:
    """A view holding exactly these records (`records` is a cached_property, so it is injected)."""
    view = KBView(cfg=kb.cfg, files={})
    view.__dict__["records"] = list(recs)
    return view


GOLDEN = (
    "# Review index (generated by `kblam review index`; do not edit by hand)\n"
    "\n"
    "## Challenges\n"
    "\n"
    "### ./resources/mx-docs/notes/full-scan-trace.md\n"
    "\n"
    "| ID | Lines | Classification | Status | Findings |\n"
    "|---|---|---|---|---|\n"
    "| SC-0001 | 63-65 | contradicted | confirmed | F-0012 |\n"
    "| SC-0004 | 70-70 | unsupported | open |  |\n"
    "| SC-0002 | 3-3 | wrong_model | rejected | F-0012, F-0003 |\n"
    "\n"
    "### resources/mx-docs/notes/other-trace.md\n"
    "\n"
    "| ID | Lines | Classification | Status | Findings |\n"
    "|---|---|---|---|---|\n"
    "| SC-0003 | 2-4 | contradicted | stale | F-0007 |\n"
    "\n"
    "## Tasks\n"
    "\n"
    "| ID | Finding | Kind | Status | Question |\n"
    "|---|---|---|---|---|\n"
    "| CT-0002 | F-0001 | confirmation | confirmed | Does a second capture reproduce the ratio? |\n"
    "| CT-0001 | F-0002 | replication | open | Does an independent measurement establish the claim \\| "
    "at 0.1%? Across both rows. |\n"
    "\n"
    "## Uses\n"
    "\n"
    "| ID | Challenge | Finding | Excerpt | Disposition | Status |\n"
    "|---|---|---|---|---|---|\n"
    "| CU-0001 | SC-0001 | F-0012 | 2 | rewritten_claim | approved |\n"
).encode("utf-8")

EMPTY = (
    "# Review index (generated by `kblam review index`; do not edit by hand)\n"
    "\n"
    "## Challenges\n"
    "\n"
    "None.\n"
    "\n"
    "## Tasks\n"
    "\n"
    "None.\n"
    "\n"
    "## Uses\n"
    "\n"
    "None.\n"
).encode("utf-8")


def test_review_index_golden(kb):
    """Row orders: challenges by assertion sha256, occurrence, ID and grouped by canonical key (the
    "./" and the backslash spelling of one path are one group, headed by the first row's spelling);
    tasks by finding, ID; uses by challenge, ID."""
    view = view_of(kb, [
        record("SC", "SC-0001", source=source("./" + TRACE, sha256="a" * 64, lines=(63, 65)),
               status="confirmed", classification="contradicted", linked_findings=["F-0012"]),
        record("SC", "SC-0002", source=source(TRACE.replace("/", "\\"), sha256="b" * 64, lines=(3, 3)),
               status="rejected", classification="wrong_model", linked_findings=["F-0012", "F-0003"]),
        record("SC", "SC-0004", source=source(TRACE, sha256="a" * 64, occurrence=2, lines=(70, 70)),
               status="open", classification="unsupported", linked_findings=[]),
        record("SC", "SC-0003", source=source(OTHER, sha256="c" * 64, lines=(2, 4)),
               status="stale", classification="contradicted", linked_findings=["F-0007"]),
        records.Record(path=f"{REVIEW}/challenges/SC-0009.yaml", id="SC-0009", kind="SC", data=None,
                       raw=b"\xff\xfe", error="not UTF-8"),
        records.Record(path=f"{REVIEW}/tasks/notes.yaml", id=None, kind=None,
                       data=record_data("CT", "CT-0010"), raw=b""),
        record("CT", "CT-0001", finding="F-0002", kind="replication", status="open",
               question="Does an independent measurement establish the claim | at 0.1%?\nAcross both rows."),
        record("CT", "CT-0002", finding="F-0001", kind="confirmation", status="confirmed",
               question="Does a second capture reproduce the ratio?"),
        record("CU", "CU-0001", challenge="SC-0001", finding="F-0012", disposition="rewritten_claim",
               status="approved",
               citation={"ordinal": 2, "path": TRACE, "range": [63, 65], "tag_sha256": ZERO64}),
    ])
    assert generate_review_index(view) == GOLDEN


def test_review_index_without_records(kb):
    out = generate_review_index(view_of(kb, []))
    assert out == EMPTY
    assert out.startswith(HEADER.encode("utf-8") + b"\n")


def test_review_index_leaves_out_unparsed_and_unnamed(kb):
    """A record whose data did not parse, and one whose name gives no kind, are both left out."""
    view = view_of(kb, [
        records.Record(path=f"{REVIEW}/challenges/SC-0001.yaml", id="SC-0001", kind="SC", data=None,
                       raw=b"\xff\xfe", error="not UTF-8"),
        records.Record(path=f"{REVIEW}/tasks/notes.yaml", id=None, kind=None,
                       data=record_data("CT", "CT-0001"), raw=b""),
    ])
    assert generate_review_index(view) == EMPTY


def test_review_index_refused_path_keys_as_written(kb, monkeypatch):
    """A path canonical_key refuses still groups, under the path as written (SPEC §5.2.5)."""
    def refuse(cfg, raw: str) -> str:
        if raw.startswith("/"):
            raise paths.PathRefused("absolute path")
        return raw
    monkeypatch.setattr(paths, "canonical_key", refuse)
    view = view_of(kb, [record("SC", "SC-0001", source=source("/outside/trace.md"))])
    text = generate_review_index(view).decode("utf-8")
    assert "### /outside/trace.md" in text
    assert "| SC-0001 | 3-3 | contradicted | open |  |" in text


def test_review_index_escapes_cells(kb):
    """A `|` is escaped and a newline collapsed, as index._cell does; the document is LF, one final \n."""
    view = view_of(kb, [
        record("CT", "CT-0001", question="Does the ratio hold | within 0.1%?\nAcross both rows."),
        record("CU", "CU-0001", citation={"ordinal": 3, "path": TRACE, "range": [1, 2],
                                          "tag_sha256": ZERO64}),
    ])
    out = generate_review_index(view)
    text = out.decode("utf-8")
    assert ("| CT-0001 | F-0001 | replication | open | "
            "Does the ratio hold \\| within 0.1%? Across both rows. |") in text
    assert "| CU-0001 | SC-0001 | F-0001 | 3 | unaffected_raw_bytes | open |" in text
    assert text.splitlines()[0] == HEADER
    assert "\r" not in text
    assert out.endswith(b"\n") and not out.endswith(b"\n\n")


def test_review_index_uses_order_by_challenge_then_id(kb):
    view = view_of(kb, [
        record("CU", "CU-0001", challenge="SC-0002"),
        record("CU", "CU-0002", challenge="SC-0001"),
    ])
    rows = [line for line in generate_review_index(view).decode("utf-8").splitlines()
            if line.startswith("| CU-")]
    assert rows == ["| CU-0002 | SC-0001 | F-0001 | 1 | unaffected_raw_bytes | open |",
                    "| CU-0001 | SC-0002 | F-0001 | 1 | unaffected_raw_bytes | open |"]
