"""Generate `findings/INDEX.md` from frontmatter (SPEC §7 `kblam index`)."""

from __future__ import annotations

from collections import defaultdict

from kblam.view import KBView

HEADER = "# Findings index (generated by `kblam index`; do not edit by hand)"


def _cell(value) -> str:
    if value is None:
        return ""
    if isinstance(value, list):
        value = ", ".join(str(v) for v in value)
    return " ".join(str(value).split()).replace("|", r"\|")


def generate_index(view: KBView) -> bytes:
    by_topic: dict[str, list[str]] = defaultdict(list)
    for finding in view.findings:  # already in ID order
        rel = view.rel_to_findings(finding.path)
        topic = rel.parent.as_posix()
        meta = finding.meta if finding.ok else {}
        row = "| [{id}]({link}) | {title} | {label} | {scope} |".format(
            id=finding.file_id,
            link=rel.as_posix(),
            title=_cell(meta.get("title")),
            label=_cell(meta.get("label")),
            scope=_cell(meta.get("scope")),
        )
        by_topic[topic].append(row)

    lines = [HEADER, ""]
    if not by_topic:
        lines.append("No findings.")
    for topic in sorted(by_topic):
        lines += [f"## {topic}", "", "| ID | Title | Label | Scope |", "|---|---|---|---|"]
        lines += by_topic[topic]
        lines.append("")
    return ("\n".join(lines).rstrip("\n") + "\n").encode("utf-8")
