"""Generate `<review root>/INDEX.md` (SPEC §5.1.5 Review index)."""

from __future__ import annotations

from itertools import groupby

from kblam import paths
from kblam.index import _cell
from kblam.records import Record
from kblam.view import KBView

HEADER = "# Review index (generated by `kblam review index`; do not edit by hand)"

NONE = "None."  # a section with no records
# Column headers and the separator row index.py writes (no spaces inside the dashes).
CHALLENGE_TABLE = ("| ID | Lines | Classification | Status | Findings |", "|---|---|---|---|---|")
TASK_TABLE = ("| ID | Finding | Kind | Status | Question |", "|---|---|---|---|---|")
USE_TABLE = ("| ID | Challenge | Finding | Excerpt | Disposition | Status |", "|---|---|---|---|---|---|")


def generate_review_index(view) -> bytes:
    """The review index for view.records, deterministic, as SPEC §5.1.5 says:

    HEADER, then `## Challenges`: one `### <source path>` group per canonical source key
    (paths.canonical_key; a refused path keys as the path as written), groups in key order, each headed
    by the path as the group's first challenge (by the row order) writes it, each a table
    `| ID | Lines | Classification | Status | Findings |` with rows ordered by assertion sha256,
    occurrence and ID. `## Tasks`: `| ID | Finding | Kind | Status | Question |` ordered by finding, ID.
    `## Uses`: `| ID | Challenge | Finding | Excerpt | Disposition | Status |` ordered by challenge, ID.
    A section with no records reads `None.`. Cells via index._cell. No timestamps, no assertion text,
    no proposition. Records whose data did not parse are left out. LF endings, one final newline.
    """
    lines = [HEADER, ""]
    for section in (_challenges(view), _tasks(view), _uses(view)):
        lines += section
    return ("\n".join(lines).rstrip("\n") + "\n").encode("utf-8")


def _challenges(view: KBView) -> list[str]:
    """The `## Challenges` section: one table per canonical source key, each under its `### <path>`."""
    rows = []
    for rec in view.records:
        if rec.kind != "SC" or not isinstance(rec.data, dict):
            continue
        source = _mapping(rec.data.get("source"))
        assertion = _mapping(source.get("assertion"))
        path = _text(source.get("path"))
        row = "| {id} | {lines} | {classification} | {status} | {findings} |".format(
            id=_cell(_id(rec)),
            lines=_cell(_lines(assertion.get("lines"))),
            classification=_cell(_text(rec.data.get("classification"))),
            status=_cell(_text(rec.data.get("status"))),
            findings=_findings(rec.data.get("linked_findings")),
        )
        sort = (_key(view, path), _text(assertion.get("sha256")),
                _order_int(assertion.get("occurrence")), _id(rec))
        rows.append((sort, path, row))

    if not rows:
        return ["## Challenges", "", NONE, ""]
    rows.sort(key=lambda row: row[0])
    lines = ["## Challenges", ""]
    for _sort, same_key in groupby(rows, key=lambda row: row[0][0]):
        group = list(same_key)
        lines += [f"### {group[0][1]}", "", *CHALLENGE_TABLE]
        lines += [row for _sort, _path, row in group]
        lines.append("")
    return lines


def _tasks(view: KBView) -> list[str]:
    """The `## Tasks` section, in order of finding, then ID."""
    rows = []
    for rec in view.records:
        if rec.kind != "CT" or not isinstance(rec.data, dict):
            continue
        row = "| {id} | {finding} | {kind} | {status} | {question} |".format(
            id=_cell(_id(rec)),
            finding=_cell(_text(rec.data.get("finding"))),
            kind=_cell(_text(rec.data.get("kind"))),
            status=_cell(_text(rec.data.get("status"))),
            question=_cell(_text(rec.data.get("question"))),
        )
        rows.append(((_text(rec.data.get("finding")), _id(rec)), row))

    if not rows:
        return ["## Tasks", "", NONE, ""]
    rows.sort(key=lambda row: row[0])
    return ["## Tasks", "", *TASK_TABLE] + [row for _sort, row in rows] + [""]


def _uses(view: KBView) -> list[str]:
    """The `## Uses` section, in order of challenge, then ID."""
    rows = []
    for rec in view.records:
        if rec.kind != "CU" or not isinstance(rec.data, dict):
            continue
        citation = _mapping(rec.data.get("citation"))
        row = "| {id} | {challenge} | {finding} | {excerpt} | {disposition} | {status} |".format(
            id=_cell(_id(rec)),
            challenge=_cell(_text(rec.data.get("challenge"))),
            finding=_cell(_text(rec.data.get("finding"))),
            excerpt=_ordinal(citation.get("ordinal")),
            disposition=_cell(_text(rec.data.get("disposition"))),
            status=_cell(_text(rec.data.get("status"))),
        )
        rows.append(((_text(rec.data.get("challenge")), _id(rec)), row))

    if not rows:
        return ["## Uses", "", NONE, ""]
    rows.sort(key=lambda row: row[0])
    return ["## Uses", "", *USE_TABLE] + [row for _sort, row in rows] + [""]


def _key(view: KBView, path: str) -> str:
    """A source path's canonical key; a refused path keys as the path as written (SPEC §5.1.5)."""
    try:
        return paths.canonical_key(view.cfg, path)
    except paths.PathRefused:
        return path


def _id(rec: Record) -> str:
    """The ID a row is filed under: the filename's, as view.records gives it, or "" when it gives none."""
    return rec.id if rec.id is not None else ""


def _mapping(value) -> dict:
    """A mapping value, or {} when it is missing or of the wrong type."""
    return value if isinstance(value, dict) else {}


def _text(value) -> str:
    """A string value, or "" when it is missing or of the wrong type. Sorts None and wrong types first."""
    return value if isinstance(value, str) else ""


def _order_int(value) -> int:
    """An integer sorting key: a missing or wrongly typed value sorts first (a boolean is not an integer)."""
    return value if isinstance(value, int) and not isinstance(value, bool) else 0


def _lines(value) -> str:
    """An assertion's `lines` as "A-B"; "" when it is missing or not a list of integers."""
    if not isinstance(value, (list, tuple)) or not value:
        return ""
    if any(not isinstance(v, int) or isinstance(v, bool) for v in value):
        return ""
    return "-".join(str(v) for v in value)


def _ordinal(value) -> str:
    """A citation's `ordinal` as a cell: the number alone; a missing or wrongly typed value is empty."""
    return _cell(value) if isinstance(value, int) and not isinstance(value, bool) else ""


def _findings(value) -> str:
    """A `linked_findings` list as a cell, joined with ", "; a missing or wrongly typed value is empty."""
    return _cell(value) if isinstance(value, list) else ""
